# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Python settings and pip install
python:
  install:
    - method: pip
      path: .  # Install your package via setup.py
    - requirements: requirements.txt  # Project-wide pip dependencies

sphinx:
  configuration: docs/conf.py
