package:
  name: "dashingturtle"
  version: "0.1.3"

source:
  path: ..

requirements:
  host:
    - python =3.9
    - pip

  run:
    - python =3.9
    - setuptools <81
    - asttokens ==2.4.1
    - bcrypt ==4.2.0
    - cffi ==1.17.1
    - colorama ==0.4.6
    - colour ==0.1.5
    - contourpy ==1.2.1
    - cryptography
    - cycler ==0.12.1
    - decorator ==5.1.1
    - deprecated ==1.2.14
    - drawsvg ==2.4.0
    - executing ==2.0.1
    - filelock ==3.14.0
    - fonttools ==4.51.0
    - fsspec ==2024.5.0
    - greenlet ==3.1.1
    - iniconfig ==2.1.0
    - ipython
    - jedi ==0.19.1
    - joblib ==1.4.2
    - kiwisolver ==1.4.5
    - kmodes ==0.12.2
    - mariadb ==1.1.10
    - markdown-it-py ==3.0.0
    - matplotlib-inline ==0.1.7
    - matplotlib-venn ==1.1.1
    - mysql-connector-python
    - mdurl ==0.1.2
    - mpmath ==1.3.0
    - networkx
    - numpy ==1.26.4
    - packaging ==24.0
    - pandas ==2.2.2
    - paramiko ==3.5.0
    - parso ==0.8.4
    - pexpect ==4.9.0
    - pillow ==10.3.0
    - platformdirs ==4.2.2
    - pluggy ==1.6.0
    - prompt-toolkit ==3.0.47
    - ptyprocess ==0.7.0
    - pure_eval ==0.2.3
    - pycparser ==2.22
    - pygments ==2.18.0
    - pymysql ==1.1.1
    - pynacl ==1.5.0
    - pyparsing ==3.1.2
    - pysam ==0.23.0
    - pytest ==8.4.1
    - python-dateutil ==2.9.0.post0
    - pytz ==2024.1
    - pyyaml ==6.0.2
    - rich ==14.0.0
    - scikit-learn
    - scipy ==1.13.0
    - seaborn ==0.13.2
    - six ==1.16.0
    - snowflake-id ==1.0.2
    - sqlalchemy ==2.0.36
    - sshtunnel ==0.4.0
    - stack_data ==0.6.3
    - svgwrite ==1.4.3
    - sympy ==1.12.1
    - threadpoolctl ==3.5.0
    - pytorch
    - traitlets ==5.14.3
    - typing-extensions ==4.12.1
    - wcwidth ==0.2.13
    - wrapt ==1.16.0
    - markupsafe ==2.0  # ← this also must be from conda channel

about:
  home: https://github.com/jwbear/Dashing_Turtle
  license: MIT
  summary: "An application for building structural landscapes of RNA sequence modifications with Nanopore data."

extra:
  recipe-maintainers:
    - jwbear
