package:
  name: "dashingturtle"
  version: "0.1.7"

source:
  path: ..

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

include:
  - wheels/*

requirements:
  host:
    - python =3.11
    - pip
  run:
    - python =3.11
    - pip

about:
  home: https://github.com/jwbear/Dashing_Turtle
  license: MIT
  summary: "An application for building structural landscapes of RNA sequence modifications with Nanopore data."

extra:
  recipe-maintainers:
    - jwbear
  channels:
    - conda-forge
    - defaults
