---
name: Conda Build & Upload

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: "true"
          python-version: ${{ matrix.python-version }}
          channels: jwbear,bioconda,conda-forge
          use-only-tar-bz2: true

      - name: Create conda build environment
        run: conda create -n build-env python=${{ matrix.python-version }} -y

      - name: Install build dependencies
        run: conda install -n build-env -c conda-forge conda-build anaconda-client conda-verify libarchive -y

      - name: Build Conda package
        run: |
          conda config --set anaconda_upload no
          conda run -n build-env conda build conda-recipe --python ${{ matrix.python-version }}

      - name: Upload to Anaconda (main branch only)
        if: github.ref == 'refs/heads/main'
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          echo "Getting build output path..."
          BUILT_PACKAGE=$(conda build conda-recipe --python ${{ matrix.python-version }} --output)
          echo "Uploading: $BUILT_PACKAGE"
          anaconda -t $ANACONDA_API_TOKEN upload --user jwbear --force "$BUILT_PACKAGE"
