---
name: Conda Build & Upload

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: build-env
          channels: conda-forge, bioconda
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true

      - name: Set channel priority
        run: |
          conda config --add channels conda-forge
          conda config --add channels defaults
          conda config --set channel_priority strict

      - name: Create conda build environment
        run: conda create -n build-env python=${{ matrix.python-version }} -y

      - name: Install build dependencies
        run: conda install -n build-env -c conda-forge conda-build anaconda-client conda-verify libarchive -y

      - name: Build Conda package
        run: |
          conda config --set anaconda_upload no
          conda run -n build-env conda build conda-recipe --python ${{ matrix.python-version }}

#      - name: Upload to Anaconda (Unix)
#        if: runner.os != 'Windows' && github.ref == 'refs/heads/main'
#        env:
#          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
#        run: |
#          echo "Getting build output path..."
#          BUILT_PACKAGE=$(conda run -n build-env conda build conda-recipe --python ${{ matrix.python-version }} --output)
#          echo "Uploading: $BUILT_PACKAGE"
#          conda run -n build-env anaconda -t $ANACONDA_API_TOKEN upload --user jwbear --force "$BUILT_PACKAGE"
#
#      - name: Upload to Anaconda (Windows)
#        if: runner.os == 'Windows' && github.ref == 'refs/heads/main'
#        env:
#          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
#        shell: pwsh
#        run: |
#          Write-Output "Setting up Conda environment..."
#          $env:Path += ";C:\Miniconda\Scripts;C:\Miniconda;C:\Miniconda\Library\bin"
#          conda init powershell
#          & $env:USERPROFILE\Documents\WindowsPowerShell\profile.ps1  # Load conda if needed
#          conda activate build-env
#
#          Write-Output "Getting build output path..."
#          $BUILT_PACKAGE = conda build conda-recipe --python ${{ matrix.python-version }} --output
#
#          Write-Output "Uploading: $BUILT_PACKAGE"
#          anaconda -t $env:ANACONDA_API_TOKEN upload --user jwbear --force $BUILT_PACKAGE
